### PR TITLE
Implement and use Silver extension for AST construction using concrete syntax

### PR DESCRIPTION
**Pull request by krame505**

### CODE REVIEW

**Comment by krame505** [comment]
This provides a Silver extension ("Silver-Oberon0") with quoting and antiquoting for AST construction and patterns.  There aren't currently any "fancy" antiquote productions for lists, particular productions, etc. as there isn't a need.  

I also made a few changes to use the concrete syntax construction quote productions in a few places, but the pattern matching ones are not currently used anywhere.  I modified the `build-all-artifacts` script to build Silver-Oberon0 first, then use that jar to build all the various artifact jars.  

This all is fine, but I have no idea if it actually works.  @ericvanwyk do you know if there are some test cases somewhere?  If so we should really get those set up with Jenkins at some point.

**Review by ericvanwyk — COMMENTED** [review]
Before approving this, can you look at the Oberon0 paper to see if we are giving pointers there to files in this repo?  I'm wondering if we should do the renaming of files into a ``grammars`` directory.  The paper may give file paths names that don't include this.  Can you check?

**Comment by krame505** [comment]
Where can I find that paper?  The pdf link on your website is a 404.
Lucas Kramer

**Comment by ericvanwyk** [comment]
WTF - do none of these work! Arg... :)

Try this:
https://www.sciencedirect.com/science/article/pii/S0167642315003020

**Comment by krame505** [comment]
Thanks, I don't see any direct links to files in the repo from the paper.  It only references grammar names and gives a link to the DOI.  

Also there were a few annoying hacks that I would like to eventually fix here (and in silver-ableC) due to Silver's broken concept of layout.  Also lexer class name resolution in Silver is broken/never finished, which required an annoying workaround - that is on my TODO list to fix here as well.

**Review by ericvanwyk — APPROVED** [review]

**Pull request merged**
